<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GIAM Access & Compliance Report</title>
    <style>
        @page {
            margin: 25px 25px 35px 25px;
        }
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 9px;
            color: #1e293b;
            line-height: 1.3;
        }
        .header-table {
            width: 100%;
            border-bottom: 2px solid #0284c7;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }
        .title {
            font-size: 16px;
            font-weight: bold;
            color: #0f172a;
            margin: 0;
        }
        .subtitle {
            font-size: 10px;
            color: #64748b;
            margin-top: 2px;
        }
        .meta-text {
            text-align: right;
            font-size: 8.5px;
            color: #64748b;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .data-table th {
            background-color: #f1f5f9;
            color: #334155;
            font-weight: 600;
            text-align: left;
            padding: 6px 4px;
            border-bottom: 1px solid #cbd5e1;
            font-size: 8.5px;
        }
        .data-table td {
            padding: 5px 4px;
            border-bottom: 1px solid #e2e8f0;
            vertical-align: top;
        }
        .data-table tr:nth-child(even) td {
            background-color: #f8fafc;
        }
        .badge {
            display: inline-block;
            padding: 1px 4px;
            border-radius: 3px;
            font-weight: bold;
            font-size: 7.5px;
        }
        .badge-active {
            background-color: #dcfce7;
            color: #166534;
        }
        .badge-revoked {
            background-color: #fee2e2;
            color: #991b1b;
        }
        .badge-pending {
            background-color: #fef9c3;
            color: #854d0e;
        }
        .footer {
            position: fixed;
            bottom: -20px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 8px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 4px;
        }
    </style>
</head>
<body>
    <table class="header-table">
        <tr>
            <td>
                <h1 class="title">Global Identity & Access Management</h1>
                <div class="subtitle">Official User Project Access & Compliance Audit Matrix</div>
            </td>
            <td class="meta-text">
                <div><strong>Generated At:</strong> {{ $generatedAt }}</div>
                <div><strong>Generated By:</strong> {{ $generatedBy }}</div>
                <div><strong>Total Records:</strong> {{ count($accessRecords) }}</div>
            </td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 10%;">Employee</th>
                <th style="width: 15%;">Full Name</th>
                <th style="width: 12%;">Department</th>
                <th style="width: 10%;">Project</th>
                <th style="width: 8%;">Status</th>
                <th style="width: 25%;">Assigned Roles</th>
                <th style="width: 20%;">Direct Permissions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($accessRecords as $access)
                <tr>
                    <td>
                        <strong>{{ $access->user?->employee_code ?? 'N/A' }}</strong><br>
                        <span style="color: #64748b;">{{ $access->user?->username }}</span>
                    </td>
                    <td>
                        {{ $access->user?->employee?->full_name ?? $access->user?->name }}<br>
                        <span style="color: #64748b; font-size: 8px;">{{ $access->user?->email }}</span>
                    </td>
                    <td>
                        {{ $access->user?->employee?->department?->name ?? $access->user?->employee?->department_code ?? 'General' }}
                    </td>
                    <td>
                        <strong>{{ $access->project?->code }}</strong><br>
                        <span style="color: #64748b; font-size: 8px;">{{ $access->project?->name }}</span>
                    </td>
                    <td>
                        @php
                            $badgeClass = match($access->status) {
                                'ACTIVE' => 'badge-active',
                                'REVOKED' => 'badge-revoked',
                                default => 'badge-pending'
                            };
                        @endphp
                        <span class="badge {{ $badgeClass }}">{{ $access->status }}</span>
                    </td>
                    <td>
                        {{ $access->roles->pluck('name')->implode(', ') ?: 'None' }}
                    </td>
                    <td>
                        {{ $access->permissions->pluck('name')->implode(', ') ?: 'None' }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center; padding: 20px; color: #94a3b8;">
                        No access records match the selected filter criteria.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        CONFIDENTIAL & PROPRIETARY — Global Identity and Access Management System — Page generated for compliance review.
    </div>
</body>
</html>
