<?php
namespace App\Http\Controllers\V1;
use App\Http\Controllers\Controller; use App\Models\User; use Barryvdh\DomPDF\Facade\Pdf; use Illuminate\Http\Request; use Illuminate\Routing\Controllers\HasMiddleware; use Illuminate\Routing\Controllers\Middleware; use Illuminate\Support\Facades\DB;
class ReportController extends Controller implements HasMiddleware
{
 public static function middleware():array{return [new Middleware('permission:Report Index',only:['accessSummary','exportAccessSummary'])];}
 public function accessSummary(Request $request){try{return response()->json(['status'=>'success','message'=>'Access summary retrieved successfully','data'=>$this->data($request)]);}catch(\Throwable $e){return response()->json(['status'=>'error','message'=>'Failed to retrieve access summary'],500);}}
 public function exportAccessSummary(Request $request){try{$rows=$this->data($request,10000)['data'];$format=$request->query('format','csv');if($format==='pdf'){ $html='<html><body><h1>GIAM Access Report</h1><table border="1" cellspacing="0" cellpadding="5"><tr><th>Project</th><th>Role</th><th>User</th><th>Email</th><th>Permission Groups</th><th>Permissions</th></tr>';foreach($rows as $r){$html.='<tr><td>'.e($r['application_name']).'</td><td>'.e($r['role_name']).'</td><td>'.e($r['user_name']).'</td><td>'.e($r['user_email']).'</td><td>'.e(implode(', ',$r['permission_groups'])).'</td><td>'.e(implode(', ',$r['permissions'])).'</td></tr>';}return Pdf::loadHTML($html.'</table></body></html>')->download('giam-access-report.pdf');}return response()->streamDownload(function()use($rows){$h=fopen('php://output','w');fputcsv($h,['Project','Role','User Name','Email','Permission Groups','Permissions']);foreach($rows as $r)fputcsv($h,[$r['application_name'],$r['role_name'],$r['user_name'],$r['user_email'],implode(', ',$r['permission_groups']),implode(', ',$r['permissions'])]);fclose($h);},'giam-access-report.csv',['Content-Type'=>'text/csv']);}catch(\Throwable){return response()->json(['status'=>'error','message'=>'Failed to export access report'],500);}}
 private function data(Request $request,int $limitOverride=null):array{
  $perPage=min((int)$request->query('per_page',100),$limitOverride??100);$page=max((int)$request->query('page',1),1);
  $q=DB::table('model_has_roles as m')->join('users as u','m.model_id','=','u.id')->join('roles as r','m.role_id','=','r.id')->join('applications as a','r.application_id','=','a.id')->where('m.model_type',User::class)->select('a.id as application_id','a.name as application_name','r.id as role_id','r.name as role_name','u.id as user_id','u.name as user_name','u.email as user_email');
  if($request->filled('application_id'))$q->where('a.id',$request->integer('application_id')); if($request->filled('role_id'))$q->where('r.id',$request->integer('role_id')); if($request->filled('user_id'))$q->where('u.id',$request->integer('user_id')); if($request->filled('search')){$x=$request->string('search');$q->where(fn($w)=>$w->where('u.name','like',"%$x%")->orWhere('u.email','like',"%$x%"));}
  $total=(clone $q)->count();$rows=$q->orderBy('a.name')->orderBy('u.name')->offset(($page-1)*$perPage)->limit($perPage)->get();$roleIds=$rows->pluck('role_id')->unique();
  $roleGroups=DB::table('role_permission_group as rpg')->join('permission_groups as pg','pg.id','=','rpg.permission_group_id')->whereIn('rpg.role_id',$roleIds)->get(['rpg.role_id','pg.name']);
  $rolePerms=DB::table('role_has_permissions as rhp')->join('permissions as p','p.id','=','rhp.permission_id')->whereIn('rhp.role_id',$roleIds)->get(['rhp.role_id','p.name']);
  $direct=DB::table('model_has_permissions as mhp')->join('permissions as p','p.id','=','mhp.permission_id')->where('mhp.model_type',User::class)->whereIn('mhp.model_id',$rows->pluck('user_id')->unique())->get(['mhp.model_id','p.name']);
  $groups=$roleGroups->groupBy('role_id');$rp=$rolePerms->groupBy('role_id');$dp=$direct->groupBy('model_id');
  $data=$rows->map(fn($r)=>['application_id'=>$r->application_id,'application_name'=>$r->application_name,'role_id'=>$r->role_id,'role_name'=>$r->role_name,'user_id'=>$r->user_id,'user_name'=>$r->user_name,'user_email'=>$r->user_email,'permission_groups'=>($groups[$r->role_id]??collect())->pluck('name')->unique()->values()->all(),'permissions'=>collect([($rp[$r->role_id]??collect())->pluck('name'),($dp[$r->user_id]??collect())->pluck('name')])->flatten()->unique()->values()->all()])->values()->all();
  return ['data'=>$data,'total'=>$total,'page'=>$page,'per_page'=>$perPage,'last_page'=>$perPage?ceil($total/$perPage):1];
 }
}
